package GUI;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;

/**
 * ViewDesign 
 * @author Tamati Rudd
 */
public class ViewDesign extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form View
     */
    public ViewDesign() {
        this.setLocationRelativeTo(null);
        initComponents();
        this.setVisible(true);
        //add components of initial UI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setupPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        newGame = new javax.swing.JButton();
        playerTwoName = new javax.swing.JTextField();
        playerOneName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gamePanel = new javax.swing.JPanel();
        p1Placements = new javax.swing.JPanel();
        A1 = new javax.swing.JRadioButton();
        A2 = new javax.swing.JRadioButton();
        A4 = new javax.swing.JRadioButton();
        A3 = new javax.swing.JRadioButton();
        A5 = new javax.swing.JRadioButton();
        A7 = new javax.swing.JRadioButton();
        A6 = new javax.swing.JRadioButton();
        A8 = new javax.swing.JRadioButton();
        A9 = new javax.swing.JRadioButton();
        A11 = new javax.swing.JRadioButton();
        A10 = new javax.swing.JRadioButton();
        A12 = new javax.swing.JRadioButton();
        xLabel1 = new javax.swing.JLabel();
        aRowLabel = new javax.swing.JLabel();
        A146 = new javax.swing.JRadioButton();
        A147 = new javax.swing.JRadioButton();
        A148 = new javax.swing.JRadioButton();
        A149 = new javax.swing.JRadioButton();
        A150 = new javax.swing.JRadioButton();
        A151 = new javax.swing.JRadioButton();
        A152 = new javax.swing.JRadioButton();
        A153 = new javax.swing.JRadioButton();
        A154 = new javax.swing.JRadioButton();
        aRowLabel1 = new javax.swing.JLabel();
        A155 = new javax.swing.JRadioButton();
        A156 = new javax.swing.JRadioButton();
        A157 = new javax.swing.JRadioButton();
        A170 = new javax.swing.JRadioButton();
        A171 = new javax.swing.JRadioButton();
        A172 = new javax.swing.JRadioButton();
        A173 = new javax.swing.JRadioButton();
        A174 = new javax.swing.JRadioButton();
        A175 = new javax.swing.JRadioButton();
        A176 = new javax.swing.JRadioButton();
        A177 = new javax.swing.JRadioButton();
        A178 = new javax.swing.JRadioButton();
        aRowLabel3 = new javax.swing.JLabel();
        A179 = new javax.swing.JRadioButton();
        A180 = new javax.swing.JRadioButton();
        A181 = new javax.swing.JRadioButton();
        A182 = new javax.swing.JRadioButton();
        A183 = new javax.swing.JRadioButton();
        A184 = new javax.swing.JRadioButton();
        A185 = new javax.swing.JRadioButton();
        A186 = new javax.swing.JRadioButton();
        A187 = new javax.swing.JRadioButton();
        A188 = new javax.swing.JRadioButton();
        A189 = new javax.swing.JRadioButton();
        A190 = new javax.swing.JRadioButton();
        aRowLabel4 = new javax.swing.JLabel();
        A191 = new javax.swing.JRadioButton();
        A192 = new javax.swing.JRadioButton();
        A193 = new javax.swing.JRadioButton();
        A194 = new javax.swing.JRadioButton();
        A195 = new javax.swing.JRadioButton();
        A196 = new javax.swing.JRadioButton();
        A197 = new javax.swing.JRadioButton();
        A198 = new javax.swing.JRadioButton();
        A199 = new javax.swing.JRadioButton();
        A200 = new javax.swing.JRadioButton();
        aRowLabel5 = new javax.swing.JLabel();
        A201 = new javax.swing.JRadioButton();
        A202 = new javax.swing.JRadioButton();
        A203 = new javax.swing.JRadioButton();
        A204 = new javax.swing.JRadioButton();
        A205 = new javax.swing.JRadioButton();
        A218 = new javax.swing.JRadioButton();
        A219 = new javax.swing.JRadioButton();
        A220 = new javax.swing.JRadioButton();
        A221 = new javax.swing.JRadioButton();
        A222 = new javax.swing.JRadioButton();
        A223 = new javax.swing.JRadioButton();
        A224 = new javax.swing.JRadioButton();
        aRowLabel7 = new javax.swing.JLabel();
        A225 = new javax.swing.JRadioButton();
        A226 = new javax.swing.JRadioButton();
        A227 = new javax.swing.JRadioButton();
        A228 = new javax.swing.JRadioButton();
        A229 = new javax.swing.JRadioButton();
        A230 = new javax.swing.JRadioButton();
        A231 = new javax.swing.JRadioButton();
        A232 = new javax.swing.JRadioButton();
        A233 = new javax.swing.JRadioButton();
        A234 = new javax.swing.JRadioButton();
        A235 = new javax.swing.JRadioButton();
        A236 = new javax.swing.JRadioButton();
        aRowLabel8 = new javax.swing.JLabel();
        A237 = new javax.swing.JRadioButton();
        A238 = new javax.swing.JRadioButton();
        A239 = new javax.swing.JRadioButton();
        A240 = new javax.swing.JRadioButton();
        A241 = new javax.swing.JRadioButton();
        A242 = new javax.swing.JRadioButton();
        A243 = new javax.swing.JRadioButton();
        A244 = new javax.swing.JRadioButton();
        A245 = new javax.swing.JRadioButton();
        A246 = new javax.swing.JRadioButton();
        A247 = new javax.swing.JRadioButton();
        A248 = new javax.swing.JRadioButton();
        aRowLabel9 = new javax.swing.JLabel();
        A249 = new javax.swing.JRadioButton();
        A250 = new javax.swing.JRadioButton();
        A251 = new javax.swing.JRadioButton();
        A252 = new javax.swing.JRadioButton();
        A253 = new javax.swing.JRadioButton();
        A254 = new javax.swing.JRadioButton();
        A255 = new javax.swing.JRadioButton();
        A256 = new javax.swing.JRadioButton();
        A257 = new javax.swing.JRadioButton();
        A258 = new javax.swing.JRadioButton();
        A259 = new javax.swing.JRadioButton();
        A260 = new javax.swing.JRadioButton();
        aRowLabel10 = new javax.swing.JLabel();
        A261 = new javax.swing.JRadioButton();
        A262 = new javax.swing.JRadioButton();
        A263 = new javax.swing.JRadioButton();
        A264 = new javax.swing.JRadioButton();
        A265 = new javax.swing.JRadioButton();
        A266 = new javax.swing.JRadioButton();
        A267 = new javax.swing.JRadioButton();
        aRowLabel11 = new javax.swing.JLabel();
        A268 = new javax.swing.JRadioButton();
        A269 = new javax.swing.JRadioButton();
        A270 = new javax.swing.JRadioButton();
        A271 = new javax.swing.JRadioButton();
        A272 = new javax.swing.JRadioButton();
        A273 = new javax.swing.JRadioButton();
        A274 = new javax.swing.JRadioButton();
        A275 = new javax.swing.JRadioButton();
        A276 = new javax.swing.JRadioButton();
        A277 = new javax.swing.JRadioButton();
        A278 = new javax.swing.JRadioButton();
        A279 = new javax.swing.JRadioButton();
        aRowLabel12 = new javax.swing.JLabel();
        A280 = new javax.swing.JRadioButton();
        A281 = new javax.swing.JRadioButton();
        A282 = new javax.swing.JRadioButton();
        A283 = new javax.swing.JRadioButton();
        A284 = new javax.swing.JRadioButton();
        A285 = new javax.swing.JRadioButton();
        A286 = new javax.swing.JRadioButton();
        A287 = new javax.swing.JRadioButton();
        A288 = new javax.swing.JRadioButton();
        A289 = new javax.swing.JRadioButton();
        A290 = new javax.swing.JRadioButton();
        A291 = new javax.swing.JRadioButton();
        aRowLabel13 = new javax.swing.JLabel();
        A292 = new javax.swing.JRadioButton();
        A293 = new javax.swing.JRadioButton();
        A294 = new javax.swing.JRadioButton();
        A295 = new javax.swing.JRadioButton();
        A296 = new javax.swing.JRadioButton();
        A297 = new javax.swing.JRadioButton();
        A298 = new javax.swing.JRadioButton();
        A299 = new javax.swing.JRadioButton();
        A300 = new javax.swing.JRadioButton();
        A301 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setupPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Battleships: Pre-Game");

        newGame.setText("New Game");

        playerTwoName.setText("PlayerTwo");

        playerOneName.setText("PlayerOne");

        jLabel2.setText("Player 1 Name:");

        jLabel3.setText("Player 2 Name:");

        javax.swing.GroupLayout setupPanelLayout = new javax.swing.GroupLayout(setupPanel);
        setupPanel.setLayout(setupPanelLayout);
        setupPanelLayout.setHorizontalGroup(
            setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setupPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setupPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setupPanelLayout.createSequentialGroup()
                        .addComponent(playerOneName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setupPanelLayout.createSequentialGroup()
                        .addComponent(playerTwoName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(setupPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(setupPanelLayout.createSequentialGroup()
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setupPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(newGame))
                    .addGroup(setupPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        setupPanelLayout.setVerticalGroup(
            setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setupPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerOneName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerTwoName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newGame)
                .addGap(23, 23, 23))
        );

        gamePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        p1Placements.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        A1.setBackground(new java.awt.Color(66, 161, 54));

        A2.setBackground(new java.awt.Color(220, 79, 79));

        A4.setBackground(new java.awt.Color(49, 116, 216));

        A3.setBackground(new java.awt.Color(49, 116, 216));

        A5.setBackground(new java.awt.Color(49, 116, 216));

        A7.setBackground(new java.awt.Color(49, 116, 216));

        A6.setBackground(new java.awt.Color(49, 116, 216));

        A8.setBackground(new java.awt.Color(49, 116, 216));

        A9.setBackground(new java.awt.Color(49, 116, 216));

        A11.setBackground(new java.awt.Color(49, 116, 216));

        A10.setBackground(new java.awt.Color(49, 116, 216));

        A12.setBackground(new java.awt.Color(49, 116, 216));

        xLabel1.setText("  A     B     C     D     E     F    G     H     I     J      K     L");

        aRowLabel.setText("1");

        A146.setBackground(new java.awt.Color(49, 116, 216));

        A147.setBackground(new java.awt.Color(49, 116, 216));

        A148.setBackground(new java.awt.Color(49, 116, 216));

        A149.setBackground(new java.awt.Color(49, 116, 216));

        A150.setBackground(new java.awt.Color(49, 116, 216));

        A151.setBackground(new java.awt.Color(49, 116, 216));

        A152.setBackground(new java.awt.Color(49, 116, 216));

        A153.setBackground(new java.awt.Color(49, 116, 216));

        A154.setBackground(new java.awt.Color(49, 116, 216));

        aRowLabel1.setText("2");

        A155.setBackground(new java.awt.Color(49, 116, 216));

        A156.setBackground(new java.awt.Color(49, 116, 216));

        A157.setBackground(new java.awt.Color(49, 116, 216));

        A170.setBackground(new java.awt.Color(49, 116, 216));

        A171.setBackground(new java.awt.Color(49, 116, 216));

        A172.setBackground(new java.awt.Color(49, 116, 216));

        A173.setBackground(new java.awt.Color(49, 116, 216));

        A174.setBackground(new java.awt.Color(49, 116, 216));

        A175.setBackground(new java.awt.Color(49, 116, 216));

        A176.setBackground(new java.awt.Color(49, 116, 216));

        A177.setBackground(new java.awt.Color(49, 116, 216));

        A178.setBackground(new java.awt.Color(49, 116, 216));

        aRowLabel3.setText("3");

        A179.setBackground(new java.awt.Color(49, 116, 216));

        A180.setBackground(new java.awt.Color(49, 116, 216));

        A181.setBackground(new java.awt.Color(49, 116, 216));

        A182.setBackground(new java.awt.Color(49, 116, 216));

        A183.setBackground(new java.awt.Color(49, 116, 216));

        A184.setBackground(new java.awt.Color(49, 116, 216));

        A185.setBackground(new java.awt.Color(49, 116, 216));

        A186.setBackground(new java.awt.Color(49, 116, 216));

        A187.setBackground(new java.awt.Color(49, 116, 216));

        A188.setBackground(new java.awt.Color(49, 116, 216));

        A189.setBackground(new java.awt.Color(49, 116, 216));

        A190.setBackground(new java.awt.Color(49, 116, 216));

        aRowLabel4.setText("4");

        A191.setBackground(new java.awt.Color(49, 116, 216));

        A192.setBackground(new java.awt.Color(49, 116, 216));

        A193.setBackground(new java.awt.Color(49, 116, 216));

        A194.setBackground(new java.awt.Color(49, 116, 216));

        A195.setBackground(new java.awt.Color(49, 116, 216));

        A196.setBackground(new java.awt.Color(49, 116, 216));

        A197.setBackground(new java.awt.Color(49, 116, 216));

        A198.setBackground(new java.awt.Color(49, 116, 216));

        A199.setBackground(new java.awt.Color(49, 116, 216));

        A200.setBackground(new java.awt.Color(49, 116, 216));

        aRowLabel5.setText("5");

        A201.setBackground(new java.awt.Color(49, 116, 216));

        A202.setBackground(new java.awt.Color(49, 116, 216));

        A203.setBackground(new java.awt.Color(49, 116, 216));

        A204.setBackground(new java.awt.Color(49, 116, 216));

        A205.setBackground(new java.awt.Color(49, 116, 216));

        A218.setBackground(new java.awt.Color(49, 116, 216));

        A219.setBackground(new java.awt.Color(49, 116, 216));

        A220.setBackground(new java.awt.Color(49, 116, 216));

        A221.setBackground(new java.awt.Color(49, 116, 216));

        A222.setBackground(new java.awt.Color(49, 116, 216));

        A223.setBackground(new java.awt.Color(49, 116, 216));

        A224.setBackground(new java.awt.Color(49, 116, 216));

        aRowLabel7.setText("6");

        A225.setBackground(new java.awt.Color(49, 116, 216));

        A226.setBackground(new java.awt.Color(49, 116, 216));

        A227.setBackground(new java.awt.Color(49, 116, 216));

        A228.setBackground(new java.awt.Color(49, 116, 216));

        A229.setBackground(new java.awt.Color(49, 116, 216));

        A230.setBackground(new java.awt.Color(49, 116, 216));

        A231.setBackground(new java.awt.Color(49, 116, 216));

        A232.setBackground(new java.awt.Color(49, 116, 216));

        A233.setBackground(new java.awt.Color(49, 116, 216));

        A234.setBackground(new java.awt.Color(49, 116, 216));

        A235.setBackground(new java.awt.Color(49, 116, 216));

        A236.setBackground(new java.awt.Color(49, 116, 216));

        aRowLabel8.setText("7");

        A237.setBackground(new java.awt.Color(49, 116, 216));

        A238.setBackground(new java.awt.Color(49, 116, 216));

        A239.setBackground(new java.awt.Color(49, 116, 216));

        A240.setBackground(new java.awt.Color(49, 116, 216));

        A241.setBackground(new java.awt.Color(49, 116, 216));

        A242.setBackground(new java.awt.Color(49, 116, 216));

        A243.setBackground(new java.awt.Color(49, 116, 216));

        A244.setBackground(new java.awt.Color(49, 116, 216));

        A245.setBackground(new java.awt.Color(49, 116, 216));

        A246.setBackground(new java.awt.Color(49, 116, 216));

        A247.setBackground(new java.awt.Color(49, 116, 216));

        A248.setBackground(new java.awt.Color(49, 116, 216));

        aRowLabel9.setText("8");

        A249.setBackground(new java.awt.Color(49, 116, 216));

        A250.setBackground(new java.awt.Color(49, 116, 216));

        A251.setBackground(new java.awt.Color(49, 116, 216));

        A252.setBackground(new java.awt.Color(49, 116, 216));

        A253.setBackground(new java.awt.Color(49, 116, 216));

        A254.setBackground(new java.awt.Color(49, 116, 216));

        A255.setBackground(new java.awt.Color(49, 116, 216));

        A256.setBackground(new java.awt.Color(49, 116, 216));

        A257.setBackground(new java.awt.Color(49, 116, 216));

        A258.setBackground(new java.awt.Color(49, 116, 216));

        A259.setBackground(new java.awt.Color(49, 116, 216));

        A260.setBackground(new java.awt.Color(49, 116, 216));

        aRowLabel10.setText("9");

        A261.setBackground(new java.awt.Color(49, 116, 216));

        A262.setBackground(new java.awt.Color(49, 116, 216));

        A263.setBackground(new java.awt.Color(49, 116, 216));

        A264.setBackground(new java.awt.Color(49, 116, 216));

        A265.setBackground(new java.awt.Color(49, 116, 216));

        A266.setBackground(new java.awt.Color(49, 116, 216));

        A267.setBackground(new java.awt.Color(49, 116, 216));

        aRowLabel11.setText("10");

        A268.setBackground(new java.awt.Color(49, 116, 216));

        A269.setBackground(new java.awt.Color(49, 116, 216));

        A270.setBackground(new java.awt.Color(49, 116, 216));

        A271.setBackground(new java.awt.Color(49, 116, 216));

        A272.setBackground(new java.awt.Color(49, 116, 216));

        A273.setBackground(new java.awt.Color(49, 116, 216));

        A274.setBackground(new java.awt.Color(49, 116, 216));

        A275.setBackground(new java.awt.Color(49, 116, 216));

        A276.setBackground(new java.awt.Color(49, 116, 216));

        A277.setBackground(new java.awt.Color(49, 116, 216));

        A278.setBackground(new java.awt.Color(49, 116, 216));

        A279.setBackground(new java.awt.Color(49, 116, 216));

        aRowLabel12.setText("11");

        A280.setBackground(new java.awt.Color(49, 116, 216));

        A281.setBackground(new java.awt.Color(49, 116, 216));

        A282.setBackground(new java.awt.Color(49, 116, 216));

        A283.setBackground(new java.awt.Color(49, 116, 216));

        A284.setBackground(new java.awt.Color(49, 116, 216));

        A285.setBackground(new java.awt.Color(49, 116, 216));

        A286.setBackground(new java.awt.Color(49, 116, 216));

        A287.setBackground(new java.awt.Color(49, 116, 216));

        A288.setBackground(new java.awt.Color(49, 116, 216));

        A289.setBackground(new java.awt.Color(49, 116, 216));

        A290.setBackground(new java.awt.Color(49, 116, 216));

        A291.setBackground(new java.awt.Color(49, 116, 216));

        aRowLabel13.setText("12");

        A292.setBackground(new java.awt.Color(49, 116, 216));

        A293.setBackground(new java.awt.Color(49, 116, 216));

        A294.setBackground(new java.awt.Color(49, 116, 216));

        A295.setBackground(new java.awt.Color(49, 116, 216));

        A296.setBackground(new java.awt.Color(49, 116, 216));

        A297.setBackground(new java.awt.Color(49, 116, 216));

        A298.setBackground(new java.awt.Color(49, 116, 216));

        A299.setBackground(new java.awt.Color(49, 116, 216));

        A300.setBackground(new java.awt.Color(49, 116, 216));

        A301.setBackground(new java.awt.Color(49, 116, 216));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Player 1 Ship Placements");

        javax.swing.GroupLayout p1PlacementsLayout = new javax.swing.GroupLayout(p1Placements);
        p1Placements.setLayout(p1PlacementsLayout);
        p1PlacementsLayout.setHorizontalGroup(
            p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1PlacementsLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1PlacementsLayout.createSequentialGroup()
                        .addComponent(aRowLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(A294)
                        .addGap(0, 0, 0)
                        .addComponent(A295)
                        .addGap(0, 0, 0)
                        .addComponent(A297)
                        .addGap(0, 0, 0)
                        .addComponent(A296)
                        .addGap(0, 0, 0)
                        .addComponent(A298)
                        .addGap(0, 0, 0)
                        .addComponent(A301)
                        .addGap(0, 0, 0)
                        .addComponent(A300)
                        .addGap(0, 0, 0)
                        .addComponent(A299)
                        .addGap(0, 0, 0)
                        .addComponent(A293)
                        .addGap(0, 0, 0)
                        .addComponent(A292)
                        .addGap(0, 0, 0)
                        .addComponent(A291)
                        .addGap(0, 0, 0)
                        .addComponent(A290))
                    .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(p1PlacementsLayout.createSequentialGroup()
                            .addComponent(aRowLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(A282)
                            .addGap(0, 0, 0)
                            .addComponent(A283)
                            .addGap(0, 0, 0)
                            .addComponent(A285)
                            .addGap(0, 0, 0)
                            .addComponent(A284)
                            .addGap(0, 0, 0)
                            .addComponent(A286)
                            .addGap(0, 0, 0)
                            .addComponent(A289)
                            .addGap(0, 0, 0)
                            .addComponent(A288)
                            .addGap(0, 0, 0)
                            .addComponent(A287)
                            .addGap(0, 0, 0)
                            .addComponent(A281)
                            .addGap(0, 0, 0)
                            .addComponent(A280)
                            .addGap(0, 0, 0)
                            .addComponent(A279)
                            .addGap(0, 0, 0)
                            .addComponent(A278))
                        .addGroup(p1PlacementsLayout.createSequentialGroup()
                            .addComponent(aRowLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(A270)
                            .addGap(0, 0, 0)
                            .addComponent(A271)
                            .addGap(0, 0, 0)
                            .addComponent(A273)
                            .addGap(0, 0, 0)
                            .addComponent(A272)
                            .addGap(0, 0, 0)
                            .addComponent(A274)
                            .addGap(0, 0, 0)
                            .addComponent(A277)
                            .addGap(0, 0, 0)
                            .addComponent(A276)
                            .addGap(0, 0, 0)
                            .addComponent(A275)
                            .addGap(0, 0, 0)
                            .addComponent(A269)
                            .addGap(0, 0, 0)
                            .addComponent(A268)
                            .addGap(0, 0, 0)
                            .addComponent(A267)
                            .addGap(0, 0, 0)
                            .addComponent(A266))
                        .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(p1PlacementsLayout.createSequentialGroup()
                                .addComponent(aRowLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(A263)
                                .addGap(0, 0, 0)
                                .addComponent(A264)
                                .addGap(0, 0, 0)
                                .addComponent(A254)
                                .addGap(0, 0, 0)
                                .addComponent(A265)
                                .addGap(0, 0, 0)
                                .addComponent(A255)
                                .addGap(0, 0, 0)
                                .addComponent(A258)
                                .addGap(0, 0, 0)
                                .addComponent(A257)
                                .addGap(0, 0, 0)
                                .addComponent(A256)
                                .addGap(0, 0, 0)
                                .addComponent(A262)
                                .addGap(0, 0, 0)
                                .addComponent(A261)
                                .addGap(0, 0, 0)
                                .addComponent(A260)
                                .addGap(0, 0, 0)
                                .addComponent(A259))
                            .addGroup(p1PlacementsLayout.createSequentialGroup()
                                .addComponent(aRowLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(A227)
                                .addGap(0, 0, 0)
                                .addComponent(A228)
                                .addGap(0, 0, 0)
                                .addComponent(A218)
                                .addGap(0, 0, 0)
                                .addComponent(A229)
                                .addGap(0, 0, 0)
                                .addComponent(A219)
                                .addGap(0, 0, 0)
                                .addComponent(A222)
                                .addGap(0, 0, 0)
                                .addComponent(A221)
                                .addGap(0, 0, 0)
                                .addComponent(A220)
                                .addGap(0, 0, 0)
                                .addComponent(A226)
                                .addGap(0, 0, 0)
                                .addComponent(A225)
                                .addGap(0, 0, 0)
                                .addComponent(A224)
                                .addGap(0, 0, 0)
                                .addComponent(A223))
                            .addGroup(p1PlacementsLayout.createSequentialGroup()
                                .addComponent(aRowLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(A203)
                                .addGap(0, 0, 0)
                                .addComponent(A204)
                                .addGap(0, 0, 0)
                                .addComponent(A194)
                                .addGap(0, 0, 0)
                                .addComponent(A205)
                                .addGap(0, 0, 0)
                                .addComponent(A195)
                                .addGap(0, 0, 0)
                                .addComponent(A198)
                                .addGap(0, 0, 0)
                                .addComponent(A197)
                                .addGap(0, 0, 0)
                                .addComponent(A196)
                                .addGap(0, 0, 0)
                                .addComponent(A202)
                                .addGap(0, 0, 0)
                                .addComponent(A201)
                                .addGap(0, 0, 0)
                                .addComponent(A200)
                                .addGap(0, 0, 0)
                                .addComponent(A199))
                            .addGroup(p1PlacementsLayout.createSequentialGroup()
                                .addComponent(aRowLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(A157)
                                .addGap(0, 0, 0)
                                .addComponent(A146)
                                .addGap(0, 0, 0)
                                .addComponent(A148)
                                .addGap(0, 0, 0)
                                .addComponent(A147)
                                .addGap(0, 0, 0)
                                .addComponent(A149)
                                .addGap(0, 0, 0)
                                .addComponent(A152)
                                .addGap(0, 0, 0)
                                .addComponent(A151)
                                .addGap(0, 0, 0)
                                .addComponent(A150)
                                .addGap(0, 0, 0)
                                .addComponent(A156)
                                .addGap(0, 0, 0)
                                .addComponent(A155)
                                .addGap(0, 0, 0)
                                .addComponent(A154)
                                .addGap(0, 0, 0)
                                .addComponent(A153))
                            .addGroup(p1PlacementsLayout.createSequentialGroup()
                                .addComponent(aRowLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p1PlacementsLayout.createSequentialGroup()
                                        .addComponent(A1)
                                        .addGap(0, 0, 0)
                                        .addComponent(A2)
                                        .addGap(0, 0, 0)
                                        .addComponent(A3)
                                        .addGap(0, 0, 0)
                                        .addComponent(A4)
                                        .addGap(0, 0, 0)
                                        .addComponent(A5)
                                        .addGap(0, 0, 0)
                                        .addComponent(A6)
                                        .addGap(0, 0, 0)
                                        .addComponent(A7)
                                        .addGap(0, 0, 0)
                                        .addComponent(A8)
                                        .addGap(0, 0, 0)
                                        .addComponent(A9)
                                        .addGap(0, 0, 0)
                                        .addComponent(A10)
                                        .addGap(0, 0, 0)
                                        .addComponent(A11)
                                        .addGap(0, 0, 0)
                                        .addComponent(A12))
                                    .addComponent(xLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(p1PlacementsLayout.createSequentialGroup()
                                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aRowLabel3)
                                    .addComponent(aRowLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p1PlacementsLayout.createSequentialGroup()
                                        .addComponent(A193)
                                        .addGap(0, 0, 0)
                                        .addComponent(A182)
                                        .addGap(0, 0, 0)
                                        .addComponent(A184)
                                        .addGap(0, 0, 0)
                                        .addComponent(A183)
                                        .addGap(0, 0, 0)
                                        .addComponent(A185)
                                        .addGap(0, 0, 0)
                                        .addComponent(A188)
                                        .addGap(0, 0, 0)
                                        .addComponent(A187)
                                        .addGap(0, 0, 0)
                                        .addComponent(A186)
                                        .addGap(0, 0, 0)
                                        .addComponent(A192)
                                        .addGap(0, 0, 0)
                                        .addComponent(A191)
                                        .addGap(0, 0, 0)
                                        .addComponent(A190)
                                        .addGap(0, 0, 0)
                                        .addComponent(A189))
                                    .addGroup(p1PlacementsLayout.createSequentialGroup()
                                        .addComponent(A181)
                                        .addGap(0, 0, 0)
                                        .addComponent(A170)
                                        .addGap(0, 0, 0)
                                        .addComponent(A172)
                                        .addGap(0, 0, 0)
                                        .addComponent(A171)
                                        .addGap(0, 0, 0)
                                        .addComponent(A173)
                                        .addGap(0, 0, 0)
                                        .addComponent(A176)
                                        .addGap(0, 0, 0)
                                        .addComponent(A175)
                                        .addGap(0, 0, 0)
                                        .addComponent(A174)
                                        .addGap(0, 0, 0)
                                        .addComponent(A180)
                                        .addGap(0, 0, 0)
                                        .addComponent(A179)
                                        .addGap(0, 0, 0)
                                        .addComponent(A178)
                                        .addGap(0, 0, 0)
                                        .addComponent(A177))))
                            .addGroup(p1PlacementsLayout.createSequentialGroup()
                                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aRowLabel8)
                                    .addComponent(aRowLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p1PlacementsLayout.createSequentialGroup()
                                        .addComponent(A251)
                                        .addGap(0, 0, 0)
                                        .addComponent(A252)
                                        .addGap(0, 0, 0)
                                        .addComponent(A242)
                                        .addGap(0, 0, 0)
                                        .addComponent(A253)
                                        .addGap(0, 0, 0)
                                        .addComponent(A243)
                                        .addGap(0, 0, 0)
                                        .addComponent(A246)
                                        .addGap(0, 0, 0)
                                        .addComponent(A245)
                                        .addGap(0, 0, 0)
                                        .addComponent(A244)
                                        .addGap(0, 0, 0)
                                        .addComponent(A250)
                                        .addGap(0, 0, 0)
                                        .addComponent(A249)
                                        .addGap(0, 0, 0)
                                        .addComponent(A248)
                                        .addGap(0, 0, 0)
                                        .addComponent(A247))
                                    .addGroup(p1PlacementsLayout.createSequentialGroup()
                                        .addComponent(A239)
                                        .addGap(0, 0, 0)
                                        .addComponent(A240)
                                        .addGap(0, 0, 0)
                                        .addComponent(A230)
                                        .addGap(0, 0, 0)
                                        .addComponent(A241)
                                        .addGap(0, 0, 0)
                                        .addComponent(A231)
                                        .addGap(0, 0, 0)
                                        .addComponent(A234)
                                        .addGap(0, 0, 0)
                                        .addComponent(A233)
                                        .addGap(0, 0, 0)
                                        .addComponent(A232)
                                        .addGap(0, 0, 0)
                                        .addComponent(A238)
                                        .addGap(0, 0, 0)
                                        .addComponent(A237)
                                        .addGap(0, 0, 0)
                                        .addComponent(A236)
                                        .addGap(0, 0, 0)
                                        .addComponent(A235)))))))
                .addGap(38, 38, 38))
            .addGroup(p1PlacementsLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p1PlacementsLayout.setVerticalGroup(
            p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1PlacementsLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(xLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A1)
                    .addComponent(A2)
                    .addComponent(A3)
                    .addComponent(A4)
                    .addComponent(A5)
                    .addComponent(A6)
                    .addComponent(A7)
                    .addComponent(A8)
                    .addComponent(A9)
                    .addComponent(A10)
                    .addComponent(A11)
                    .addComponent(A12)
                    .addGroup(p1PlacementsLayout.createSequentialGroup()
                        .addComponent(aRowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addGap(0, 0, 0)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A157)
                    .addComponent(A146)
                    .addComponent(A148)
                    .addComponent(A147)
                    .addComponent(A149)
                    .addComponent(A152)
                    .addComponent(A151)
                    .addComponent(A150)
                    .addComponent(A156)
                    .addComponent(A155)
                    .addComponent(A154)
                    .addComponent(A153)
                    .addComponent(aRowLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A181)
                    .addComponent(A170)
                    .addComponent(A172)
                    .addComponent(A171)
                    .addComponent(A173)
                    .addComponent(A176)
                    .addComponent(A175)
                    .addComponent(A174)
                    .addComponent(A180)
                    .addComponent(A179)
                    .addComponent(A178)
                    .addComponent(A177)
                    .addComponent(aRowLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A193)
                    .addComponent(A182)
                    .addComponent(A184, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A183)
                    .addComponent(A185)
                    .addComponent(A188)
                    .addComponent(A187)
                    .addComponent(A186)
                    .addComponent(A192)
                    .addComponent(A191)
                    .addComponent(A190)
                    .addComponent(A189)
                    .addComponent(aRowLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A203)
                    .addComponent(A204)
                    .addComponent(A194, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A205)
                    .addComponent(A195)
                    .addComponent(A198)
                    .addComponent(A197)
                    .addComponent(A196)
                    .addComponent(A202)
                    .addComponent(A201)
                    .addComponent(A200)
                    .addComponent(A199)
                    .addComponent(aRowLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A227)
                    .addComponent(A228)
                    .addComponent(A218, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A229)
                    .addComponent(A219)
                    .addComponent(A222)
                    .addComponent(A221)
                    .addComponent(A220)
                    .addComponent(A226)
                    .addComponent(A225)
                    .addComponent(A224)
                    .addComponent(A223)
                    .addComponent(aRowLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A239)
                    .addComponent(A240)
                    .addComponent(A230, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A241)
                    .addComponent(A231)
                    .addComponent(A234)
                    .addComponent(A233)
                    .addComponent(A232)
                    .addComponent(A238)
                    .addComponent(A237)
                    .addComponent(A236)
                    .addComponent(A235)
                    .addComponent(aRowLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A251)
                    .addComponent(A252)
                    .addComponent(A242, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A253)
                    .addComponent(A243)
                    .addComponent(A246)
                    .addComponent(A245)
                    .addComponent(A244)
                    .addComponent(A250)
                    .addComponent(A249)
                    .addComponent(A248)
                    .addComponent(A247)
                    .addComponent(aRowLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A263)
                    .addComponent(A264)
                    .addComponent(A254, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A265)
                    .addComponent(A255)
                    .addComponent(A258)
                    .addComponent(A257)
                    .addComponent(A256)
                    .addComponent(A262)
                    .addComponent(A261)
                    .addComponent(A260)
                    .addComponent(A259)
                    .addComponent(aRowLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A270)
                    .addComponent(A271)
                    .addComponent(A273, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A272)
                    .addComponent(A274)
                    .addComponent(A277)
                    .addComponent(A276)
                    .addComponent(A275)
                    .addComponent(A269)
                    .addComponent(A268)
                    .addComponent(A267)
                    .addComponent(A266)
                    .addComponent(aRowLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A282)
                    .addComponent(A283)
                    .addComponent(A285, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A284)
                    .addComponent(A286)
                    .addComponent(A289)
                    .addComponent(A288)
                    .addComponent(A287)
                    .addComponent(A281)
                    .addComponent(A280)
                    .addComponent(A279)
                    .addComponent(A278)
                    .addComponent(aRowLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(p1PlacementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A294)
                    .addComponent(A295)
                    .addComponent(A297, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A296)
                    .addComponent(A298)
                    .addComponent(A301)
                    .addComponent(A300)
                    .addComponent(A299)
                    .addComponent(A293)
                    .addComponent(A292)
                    .addComponent(A291)
                    .addComponent(A290)
                    .addComponent(aRowLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p1Placements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(setupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(setupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(318, 318, 318))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(p1Placements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A1;
    private javax.swing.JRadioButton A10;
    private javax.swing.JRadioButton A11;
    private javax.swing.JRadioButton A12;
    private javax.swing.JRadioButton A146;
    private javax.swing.JRadioButton A147;
    private javax.swing.JRadioButton A148;
    private javax.swing.JRadioButton A149;
    private javax.swing.JRadioButton A150;
    private javax.swing.JRadioButton A151;
    private javax.swing.JRadioButton A152;
    private javax.swing.JRadioButton A153;
    private javax.swing.JRadioButton A154;
    private javax.swing.JRadioButton A155;
    private javax.swing.JRadioButton A156;
    private javax.swing.JRadioButton A157;
    private javax.swing.JRadioButton A170;
    private javax.swing.JRadioButton A171;
    private javax.swing.JRadioButton A172;
    private javax.swing.JRadioButton A173;
    private javax.swing.JRadioButton A174;
    private javax.swing.JRadioButton A175;
    private javax.swing.JRadioButton A176;
    private javax.swing.JRadioButton A177;
    private javax.swing.JRadioButton A178;
    private javax.swing.JRadioButton A179;
    private javax.swing.JRadioButton A180;
    private javax.swing.JRadioButton A181;
    private javax.swing.JRadioButton A182;
    private javax.swing.JRadioButton A183;
    private javax.swing.JRadioButton A184;
    private javax.swing.JRadioButton A185;
    private javax.swing.JRadioButton A186;
    private javax.swing.JRadioButton A187;
    private javax.swing.JRadioButton A188;
    private javax.swing.JRadioButton A189;
    private javax.swing.JRadioButton A190;
    private javax.swing.JRadioButton A191;
    private javax.swing.JRadioButton A192;
    private javax.swing.JRadioButton A193;
    private javax.swing.JRadioButton A194;
    private javax.swing.JRadioButton A195;
    private javax.swing.JRadioButton A196;
    private javax.swing.JRadioButton A197;
    private javax.swing.JRadioButton A198;
    private javax.swing.JRadioButton A199;
    private javax.swing.JRadioButton A2;
    private javax.swing.JRadioButton A200;
    private javax.swing.JRadioButton A201;
    private javax.swing.JRadioButton A202;
    private javax.swing.JRadioButton A203;
    private javax.swing.JRadioButton A204;
    private javax.swing.JRadioButton A205;
    private javax.swing.JRadioButton A218;
    private javax.swing.JRadioButton A219;
    private javax.swing.JRadioButton A220;
    private javax.swing.JRadioButton A221;
    private javax.swing.JRadioButton A222;
    private javax.swing.JRadioButton A223;
    private javax.swing.JRadioButton A224;
    private javax.swing.JRadioButton A225;
    private javax.swing.JRadioButton A226;
    private javax.swing.JRadioButton A227;
    private javax.swing.JRadioButton A228;
    private javax.swing.JRadioButton A229;
    private javax.swing.JRadioButton A230;
    private javax.swing.JRadioButton A231;
    private javax.swing.JRadioButton A232;
    private javax.swing.JRadioButton A233;
    private javax.swing.JRadioButton A234;
    private javax.swing.JRadioButton A235;
    private javax.swing.JRadioButton A236;
    private javax.swing.JRadioButton A237;
    private javax.swing.JRadioButton A238;
    private javax.swing.JRadioButton A239;
    private javax.swing.JRadioButton A240;
    private javax.swing.JRadioButton A241;
    private javax.swing.JRadioButton A242;
    private javax.swing.JRadioButton A243;
    private javax.swing.JRadioButton A244;
    private javax.swing.JRadioButton A245;
    private javax.swing.JRadioButton A246;
    private javax.swing.JRadioButton A247;
    private javax.swing.JRadioButton A248;
    private javax.swing.JRadioButton A249;
    private javax.swing.JRadioButton A250;
    private javax.swing.JRadioButton A251;
    private javax.swing.JRadioButton A252;
    private javax.swing.JRadioButton A253;
    private javax.swing.JRadioButton A254;
    private javax.swing.JRadioButton A255;
    private javax.swing.JRadioButton A256;
    private javax.swing.JRadioButton A257;
    private javax.swing.JRadioButton A258;
    private javax.swing.JRadioButton A259;
    private javax.swing.JRadioButton A260;
    private javax.swing.JRadioButton A261;
    private javax.swing.JRadioButton A262;
    private javax.swing.JRadioButton A263;
    private javax.swing.JRadioButton A264;
    private javax.swing.JRadioButton A265;
    private javax.swing.JRadioButton A266;
    private javax.swing.JRadioButton A267;
    private javax.swing.JRadioButton A268;
    private javax.swing.JRadioButton A269;
    private javax.swing.JRadioButton A270;
    private javax.swing.JRadioButton A271;
    private javax.swing.JRadioButton A272;
    private javax.swing.JRadioButton A273;
    private javax.swing.JRadioButton A274;
    private javax.swing.JRadioButton A275;
    private javax.swing.JRadioButton A276;
    private javax.swing.JRadioButton A277;
    private javax.swing.JRadioButton A278;
    private javax.swing.JRadioButton A279;
    private javax.swing.JRadioButton A280;
    private javax.swing.JRadioButton A281;
    private javax.swing.JRadioButton A282;
    private javax.swing.JRadioButton A283;
    private javax.swing.JRadioButton A284;
    private javax.swing.JRadioButton A285;
    private javax.swing.JRadioButton A286;
    private javax.swing.JRadioButton A287;
    private javax.swing.JRadioButton A288;
    private javax.swing.JRadioButton A289;
    private javax.swing.JRadioButton A290;
    private javax.swing.JRadioButton A291;
    private javax.swing.JRadioButton A292;
    private javax.swing.JRadioButton A293;
    private javax.swing.JRadioButton A294;
    private javax.swing.JRadioButton A295;
    private javax.swing.JRadioButton A296;
    private javax.swing.JRadioButton A297;
    private javax.swing.JRadioButton A298;
    private javax.swing.JRadioButton A299;
    private javax.swing.JRadioButton A3;
    private javax.swing.JRadioButton A300;
    private javax.swing.JRadioButton A301;
    private javax.swing.JRadioButton A4;
    private javax.swing.JRadioButton A5;
    private javax.swing.JRadioButton A6;
    private javax.swing.JRadioButton A7;
    private javax.swing.JRadioButton A8;
    private javax.swing.JRadioButton A9;
    private javax.swing.JLabel aRowLabel;
    private javax.swing.JLabel aRowLabel1;
    private javax.swing.JLabel aRowLabel10;
    private javax.swing.JLabel aRowLabel11;
    private javax.swing.JLabel aRowLabel12;
    private javax.swing.JLabel aRowLabel13;
    private javax.swing.JLabel aRowLabel3;
    private javax.swing.JLabel aRowLabel4;
    private javax.swing.JLabel aRowLabel5;
    private javax.swing.JLabel aRowLabel7;
    private javax.swing.JLabel aRowLabel8;
    private javax.swing.JLabel aRowLabel9;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton newGame;
    private javax.swing.JPanel p1Placements;
    private javax.swing.JTextField playerOneName;
    private javax.swing.JTextField playerTwoName;
    private javax.swing.JPanel setupPanel;
    private javax.swing.JLabel xLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
